import React from 'react';
import { Link } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { useReveal } from '../hooks/useReveal';
import {
  Shield,
  ArrowRight,
  CalendarRange,
  Wallet,
  FileSpreadsheet,
  KeyRound,
  Lock,
  ScrollText,
  Sparkles,
  CheckCircle2,
  Clock3,
  Users,
  TrendingUp,
} from 'lucide-react';

const FEATURES = [
  {
    icon: <Wallet size={18} />,
    title: 'Payroll statements',
    body: 'Encrypted payslips your team can view and export as PDF, generated by HR and locked after a set window.',
    points: ['AES-256 encrypted fields', 'One-click PDF export'],
    surface: '#F3F6FC',
    chip: '#DEE8F9',
    accent: '#1D4ED8',
    span: 'lg:col-span-3',
  },
  {
    icon: <CalendarRange size={18} />,
    title: 'Leave & calendar',
    body: 'Request time off, watch approvals land, and see company holidays and events on one shared calendar.',
    points: ['Approval trail with decision notes', 'Weekly holidays built in'],
    surface: '#F7F4FC',
    chip: '#E8E0F8',
    accent: '#6D28D9',
    span: 'lg:col-span-3',
  },
  {
    icon: <FileSpreadsheet size={18} />,
    title: 'Employee records',
    body: 'One directory for profiles, job details and compensation, with every field scoped strictly by role.',
    points: ['Role-scoped visibility'],
    surface: '#F2F8F4',
    chip: '#DCEFE3',
    accent: '#15803D',
    span: 'lg:col-span-2',
  },
  {
    icon: <ScrollText size={18} />,
    title: 'Audit everything',
    body: 'Every sensitive action is written to an immutable ledger you can filter and review.',
    points: ['Tamper-evident log'],
    surface: '#FDF8EF',
    chip: '#F7E9D2',
    accent: '#B45309',
    span: 'lg:col-span-2',
  },
  {
    icon: <KeyRound size={18} />,
    title: 'Access control',
    body: 'Multi-factor authentication, lockouts, and forced password rotation as standard.',
    points: ['TOTP with admin recovery'],
    surface: '#FBF4F8',
    chip: '#F6E2EC',
    accent: '#9D174D',
    span: 'lg:col-span-2',
  },
];

const STATS = [
  { value: '256-bit', label: 'Field encryption' },
  { value: '3', label: 'Role tiers' },
  { value: '100%', label: 'Actions audited' },
  { value: '2FA', label: 'On every account' },
];

const STEPS = [
  { n: '01', title: 'Create your account', body: 'Register in seconds and set up your profile with your own contact details.' },
  { n: '02', title: 'HR completes your record', body: 'Job title, salary and bank details are assigned by HR, never self-declared.' },
  { n: '03', title: 'Work from one place', body: 'Payslips, leave requests and the company calendar, all behind MFA.' },
];

const HeroPreview: React.FC = () => (
  <div className="relative">
    <div className="aurora float-slow absolute -left-10 -top-10 h-56 w-56 bg-[#C7D7F5]" />
    <div className="aurora float-slower absolute -bottom-12 -right-8 h-56 w-56 bg-[#E3D6F7]" />

    <div className="relative overflow-hidden rounded-[22px] border border-[rgba(28,25,23,0.10)] bg-white shadow-[0_36px_80px_-40px_rgba(28,25,23,0.45)]">
      {/* Mock chrome */}
      <div className="flex items-center gap-2 border-b border-[rgba(28,25,23,0.07)] bg-[#FBFAF8] px-4 py-3">
        <span className="h-2.5 w-2.5 rounded-full bg-[#E5E3DE]" />
        <span className="h-2.5 w-2.5 rounded-full bg-[#E5E3DE]" />
        <span className="h-2.5 w-2.5 rounded-full bg-[#E5E3DE]" />
        <span className="ml-3 text-[11px] font-semibold text-[#8A8580]">Worklynk · Dashboard</span>
      </div>

      <div className="flex">
        {/* Mock rail */}
        <div className="hidden w-[54px] flex-shrink-0 flex-col items-center gap-3 bg-[#14110F] py-4 sm:flex">
          <span className="flex h-8 w-8 items-center justify-center rounded-xl bg-white text-[#14110F]">
            <Shield size={14} />
          </span>
          {[Users, CalendarRange, Wallet, ScrollText].map((Icon, i) => (
            <span key={i} className="flex h-8 w-8 items-center justify-center rounded-xl text-white/35">
              <Icon size={14} />
            </span>
          ))}
        </div>

        <div className="min-w-0 flex-1 p-4 sm:p-5">
          <p className="text-[10px] font-bold uppercase tracking-[0.16em] text-[#A8A29E]">Tuesday, 21 July</p>
          <p className="font-display mt-1 text-[19px] font-bold tracking-[-0.02em] text-[#1C1917]">
            Good morning, <span className="gradient-text">rita</span>
          </p>

          <div className="mt-4 grid grid-cols-3 gap-2.5">
            {[
              { label: 'Pending', value: '3', surface: '#FDF8EF', accent: '#B45309' },
              { label: 'Approved', value: '18', surface: '#F2F8F4', accent: '#15803D' },
              { label: 'Team', value: '24', surface: '#F3F6FC', accent: '#1D4ED8' },
            ].map((s) => (
              <div key={s.label} className="rounded-xl p-2.5" style={{ background: s.surface }}>
                <p className="text-[8.5px] font-bold uppercase tracking-[0.12em] text-[#A8A29E]">{s.label}</p>
                <p className="font-display mt-1 text-[19px] font-bold leading-none" style={{ color: s.accent }}>
                  {s.value}
                </p>
              </div>
            ))}
          </div>

          {/* Mock bar chart */}
          <div className="mt-3 rounded-xl border border-[rgba(28,25,23,0.07)] p-3">
            <p className="text-[9px] font-bold uppercase tracking-[0.12em] text-[#A8A29E]">Requests by status</p>
            <div className="mt-2.5 space-y-1.5">
              {[
                { w: '78%', c: '#15803D' },
                { w: '46%', c: '#B45309' },
                { w: '22%', c: '#B91C1C' },
              ].map((b, i) => (
                <div key={i} className="h-1.5 overflow-hidden rounded-full bg-[#F2F1ED]">
                  <div className="h-full rounded-full" style={{ width: b.w, background: b.c }} />
                </div>
              ))}
            </div>
          </div>
        </div>
      </div>
    </div>

    {/* Floating accent chips */}
    <div className="float-slow absolute -right-3 top-16 hidden items-center gap-2 rounded-xl border border-[rgba(28,25,23,0.08)] bg-white px-3 py-2 shadow-lg md:flex">
      <span className="flex h-6 w-6 items-center justify-center rounded-lg bg-[#DCEFE3] text-[#15803D]">
        <CheckCircle2 size={13} />
      </span>
      <span className="text-[11px] font-bold text-[#1C1917]">Leave approved</span>
    </div>
    <div className="float-slower absolute -left-4 bottom-14 hidden items-center gap-2 rounded-xl border border-[rgba(28,25,23,0.08)] bg-white px-3 py-2 shadow-lg md:flex">
      <span className="flex h-6 w-6 items-center justify-center rounded-lg bg-[#DEE8F9] text-[#1D4ED8]">
        <Lock size={13} />
      </span>
      <span className="text-[11px] font-bold text-[#1C1917]">2FA verified</span>
    </div>
  </div>
);

export const Landing: React.FC = () => {
  const { user } = useAuth();
  useReveal();

  return (
    <div className="content-scope min-h-screen bg-[#F7F6F3] font-sans">
      {/* Sticky header */}
      <header className="sticky top-0 z-50 border-b border-[rgba(28,25,23,0.06)] bg-[#F7F6F3]/85 backdrop-blur-md">
        <div className="mx-auto flex w-full max-w-[1140px] items-center justify-between px-6 py-4">
          <Link to="/" className="group flex items-center gap-2.5">
            <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-[#14110F] text-white transition-transform duration-300 group-hover:-rotate-6">
              <Shield size={17} />
            </span>
            <span className="font-display text-[19px] font-bold tracking-[-0.02em] text-[#1C1917]">Worklynk</span>
          </Link>

          <nav className="flex items-center gap-2">
            {user ? (
              <Link
                to="/dashboard"
                className="group inline-flex items-center gap-2 rounded-xl bg-[#1C1917] px-4 py-2.5 text-[13px] font-semibold text-white transition-colors hover:bg-[#2B2724]"
              >
                Go to dashboard <ArrowRight size={15} className="nudge" />
              </Link>
            ) : (
              <>
                <Link
                  to="/login"
                  className="rounded-xl px-4 py-2.5 text-[13px] font-semibold text-[#57534E] transition-colors hover:bg-white hover:text-[#1C1917]"
                >
                  Log in
                </Link>
                <Link
                  to="/register"
                  className="group inline-flex items-center gap-2 rounded-xl bg-[#1C1917] px-4 py-2.5 text-[13px] font-semibold text-white transition-colors hover:bg-[#2B2724]"
                >
                  Get started <ArrowRight size={15} className="nudge" />
                </Link>
              </>
            )}
          </nav>
        </div>
      </header>

      {/* Hero */}
      <section className="grid-texture relative overflow-hidden">
        <div className="mx-auto grid w-full max-w-[1140px] items-center gap-14 px-6 pb-20 pt-14 lg:grid-cols-[1.05fr_1fr] lg:pt-20">
          <div className="reveal">
            <span className="inline-flex items-center gap-2 rounded-full border border-[rgba(28,25,23,0.10)] bg-white px-3.5 py-1.5 text-[11.5px] font-bold text-[#57534E]">
              <Sparkles size={13} className="text-[#B45309]" />
              Secure by default, not by upgrade
            </span>

            <h1 className="font-display mt-6 text-[46px] font-bold leading-[1.02] tracking-[-0.035em] text-[#1C1917] md:text-[64px]">
              The HR workspace your team can actually <span className="gradient-text">trust</span>.
            </h1>

            <p className="mt-6 max-w-xl text-[16.5px] leading-relaxed text-[#57534E]">
              Payslips, leave and employee records in one place, with multi-factor authentication,
              encrypted records and a complete audit trail built in from day one.
            </p>

            <div className="mt-9 flex flex-wrap items-center gap-3">
              <Link
                to={user ? '/dashboard' : '/register'}
                className="group inline-flex items-center gap-2 rounded-xl bg-[#14110F] px-6 py-3.5 text-[14px] font-semibold text-white shadow-[0_14px_30px_-14px_rgba(20,17,15,0.8)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-[#2B2724]"
              >
                {user ? 'Open your dashboard' : 'Create an account'}
                <ArrowRight size={16} className="nudge" />
              </Link>
              {!user && (
                <Link
                  to="/login"
                  className="inline-flex items-center gap-2 rounded-xl border border-[rgba(28,25,23,0.12)] bg-white px-6 py-3.5 text-[14px] font-semibold text-[#1C1917] transition-all duration-200 hover:-translate-y-0.5 hover:bg-[#FBFAF8]"
                >
                  I already have an account
                </Link>
              )}
            </div>

            <div className="mt-8 flex flex-wrap items-center gap-x-6 gap-y-2 text-[12.5px] font-medium text-[#8A8580]">
              <span className="inline-flex items-center gap-1.5">
                <CheckCircle2 size={14} className="text-[#15803D]" /> No credit card
              </span>
              <span className="inline-flex items-center gap-1.5">
                <Clock3 size={14} className="text-[#15803D]" /> Set up in minutes
              </span>
              <span className="inline-flex items-center gap-1.5">
                <Lock size={14} className="text-[#15803D]" /> GDPR export built in
              </span>
            </div>
          </div>

          <div className="reveal stagger-2">
            <HeroPreview />
          </div>
        </div>
      </section>

      {/* Stats band */}
      <section className="border-y border-[rgba(28,25,23,0.07)] bg-white">
        <div className="mx-auto grid w-full max-w-[1140px] grid-cols-2 gap-8 px-6 py-10 sm:grid-cols-4">
          {STATS.map((s, i) => (
            <div key={s.label} className={`reveal stagger-${i + 1} text-center sm:text-left`}>
              <p className="font-display text-[30px] font-bold leading-none tracking-[-0.02em] text-[#1C1917]">{s.value}</p>
              <p className="mt-2 text-[12px] font-semibold uppercase tracking-[0.12em] text-[#8A8580]">{s.label}</p>
            </div>
          ))}
        </div>
      </section>

      {/* Feature bento */}
      <section className="mx-auto w-full max-w-[1140px] px-6 py-20">
        <div className="reveal max-w-2xl">
          <p className="eyebrow">Everything in one workspace</p>
          <h2 className="font-display mt-3 text-[34px] font-bold leading-[1.08] tracking-[-0.03em] text-[#1C1917] md:text-[40px]">
            Built for the people who run the company.
          </h2>
          <p className="mt-4 text-[15.5px] leading-relaxed text-[#57534E]">
            Employees, HR managers and administrators each get exactly what they need, and nothing they don't.
          </p>
        </div>

        <div className="mt-12 grid gap-5 lg:grid-cols-6">
          {FEATURES.map((f, i) => (
            <div
              key={f.title}
              className={`reveal stagger-${(i % 5) + 1} lift group rounded-2xl p-6 ${f.span}`}
              style={{ background: f.surface, border: '1px solid rgba(28,25,23,0.07)' }}
            >
              <span
                className="flex h-11 w-11 items-center justify-center rounded-xl transition-transform duration-300 group-hover:scale-110"
                style={{ background: f.chip, color: f.accent }}
              >
                {f.icon}
              </span>
              <h3 className="font-display mt-4 text-[18px] font-bold tracking-[-0.01em] text-[#1C1917]">{f.title}</h3>
              <p className="mt-2 text-[13.5px] leading-relaxed text-[#57534E]">{f.body}</p>

              <ul className="mt-4 space-y-1.5">
                {f.points.map((p) => (
                  <li key={p} className="flex items-center gap-2 text-[12.5px] font-medium text-[#57534E]">
                    <CheckCircle2 size={13} style={{ color: f.accent }} />
                    {p}
                  </li>
                ))}
              </ul>
            </div>
          ))}
        </div>
      </section>

      {/* How it works */}
      <section className="border-t border-[rgba(28,25,23,0.07)] bg-white">
        <div className="mx-auto w-full max-w-[1140px] px-6 py-20">
          <div className="reveal max-w-xl">
            <p className="eyebrow">How it works</p>
            <h2 className="font-display mt-3 text-[34px] font-bold leading-[1.08] tracking-[-0.03em] text-[#1C1917]">
              From sign-up to first payslip.
            </h2>
          </div>

          <div className="mt-12 grid gap-6 md:grid-cols-3">
            {STEPS.map((s, i) => (
              <div key={s.n} className={`reveal stagger-${i + 1} group relative`}>
                <div className="lift rounded-2xl border border-[rgba(28,25,23,0.08)] bg-[#FBFAF8] p-6">
                  <span className="font-display text-[13px] font-bold tracking-[0.1em] text-[#A8A29E]">{s.n}</span>
                  <h3 className="font-display mt-3 text-[17px] font-bold text-[#1C1917]">{s.title}</h3>
                  <p className="mt-2 text-[13.5px] leading-relaxed text-[#57534E]">{s.body}</p>
                </div>
                {i < STEPS.length - 1 && (
                  <ArrowRight
                    size={18}
                    className="absolute -right-4 top-1/2 hidden -translate-y-1/2 text-[#D6D3CE] md:block"
                  />
                )}
              </div>
            ))}
          </div>
        </div>
      </section>

      {/* Security */}
      <section className="mx-auto w-full max-w-[1140px] px-6 py-20">
        <div className="reveal lift overflow-hidden rounded-[26px] bg-[#14110F] p-8 md:p-12">
          <div className="grid gap-10 lg:grid-cols-[1fr_1.1fr] lg:items-center">
            <div>
              <p className="text-[11px] font-bold uppercase tracking-[0.18em] text-white/45">Built secure by default</p>
              <h2 className="font-display mt-3 text-[32px] font-bold leading-[1.08] tracking-[-0.03em] text-white md:text-[38px]">
                Security isn't a settings page. It's the foundation.
              </h2>
              <p className="mt-4 max-w-md text-[14.5px] leading-relaxed text-white/60">
                Every account is protected, every sensitive field encrypted, and every action recorded
                for review.
              </p>
            </div>

            <div className="grid gap-4 sm:grid-cols-2">
              {[
                { icon: <KeyRound size={16} />, title: 'Multi-factor auth', body: 'TOTP enrolment with admin-assisted recovery.' },
                { icon: <Lock size={16} />, title: 'Encrypted at rest', body: 'Salary and bank details sealed with AES-256-GCM.' },
                { icon: <ScrollText size={16} />, title: 'Immutable audit log', body: 'Every sensitive action recorded and reviewable.' },
                { icon: <TrendingUp size={16} />, title: 'Brute-force defence', body: 'Rate limits, CAPTCHA and automatic lockouts.' },
              ].map((s) => (
                <div
                  key={s.title}
                  className="rounded-2xl border border-white/10 bg-white/[0.04] p-5 transition-colors duration-300 hover:bg-white/[0.08]"
                >
                  <span className="flex h-9 w-9 items-center justify-center rounded-xl bg-white/10 text-white">{s.icon}</span>
                  <h4 className="mt-3 text-[13.5px] font-bold text-white">{s.title}</h4>
                  <p className="mt-1.5 text-[12.5px] leading-relaxed text-white/55">{s.body}</p>
                </div>
              ))}
            </div>
          </div>
        </div>
      </section>

      {/* CTA */}
      <section className="mx-auto w-full max-w-[1140px] px-6 pb-24">
        <div className="reveal rounded-[26px] border border-[rgba(28,25,23,0.08)] bg-white p-10 text-center md:p-16">
          <h2 className="font-display mx-auto max-w-2xl text-[34px] font-bold leading-[1.08] tracking-[-0.03em] text-[#1C1917] md:text-[42px]">
            Ready to bring your HR into one place?
          </h2>
          <p className="mx-auto mt-4 max-w-lg text-[15.5px] leading-relaxed text-[#57534E]">
            Create an account and set up your profile, and your HR team handles the rest.
          </p>
          <div className="mt-8 flex flex-wrap items-center justify-center gap-3">
            <Link
              to={user ? '/dashboard' : '/register'}
              className="group inline-flex items-center gap-2 rounded-xl bg-[#14110F] px-7 py-3.5 text-[14px] font-semibold text-white shadow-[0_14px_30px_-14px_rgba(20,17,15,0.8)] transition-all duration-200 hover:-translate-y-0.5 hover:bg-[#2B2724]"
            >
              {user ? 'Open your dashboard' : 'Get started free'}
              <ArrowRight size={16} className="nudge" />
            </Link>
            {!user && (
              <Link
                to="/login"
                className="inline-flex items-center gap-2 rounded-xl border border-[rgba(28,25,23,0.12)] px-7 py-3.5 text-[14px] font-semibold text-[#1C1917] transition-all duration-200 hover:-translate-y-0.5 hover:bg-[#FBFAF8]"
              >
                Log in
              </Link>
            )}
          </div>
        </div>
      </section>

      {/* Footer */}
      <footer className="border-t border-[rgba(28,25,23,0.08)] bg-white">
        <div className="mx-auto flex w-full max-w-[1140px] flex-col items-center justify-between gap-4 px-6 py-9 sm:flex-row">
          <div className="flex items-center gap-2.5">
            <span className="flex h-8 w-8 items-center justify-center rounded-lg bg-[#14110F] text-white">
              <Shield size={15} />
            </span>
            <span className="text-[12.5px] text-[#8A8580]">© {new Date().getFullYear()} Worklynk</span>
          </div>
          <div className="flex items-center gap-6 text-[12.5px] font-semibold text-[#57534E]">
            <Link to="/login" className="transition-colors hover:text-[#1C1917]">
              Log in
            </Link>
            <Link to="/register" className="transition-colors hover:text-[#1C1917]">
              Register
            </Link>
          </div>
        </div>
      </footer>
    </div>
  );
};
