import React, { useState, useEffect } from 'react';
import { useNavigate, useLocation } from 'react-router-dom';
import { useAuth } from '../context/AuthContext';
import { AuthLayout } from '../layouts/AuthLayout';
import { Input } from '../components/Input';
import { Button } from '../components/Button';

export const MfaVerify: React.FC = () => {
  const { verifyMfa } = useAuth();
  const navigate = useNavigate();
  const location = useLocation();

  const [code, setCode] = useState('');
  const [error, setError] = useState('');
  const [loading, setLoading] = useState(false);

  const tempToken = location.state?.tempToken;

  useEffect(() => {
    if (!tempToken) {
      navigate('/login');
    }
  }, [tempToken, navigate]);

  const handleSubmit = async (e: React.FormEvent) => {
    e.preventDefault();
    if (!tempToken) return;
    
    setError('');
    setLoading(true);

    try {
      await verifyMfa(tempToken, code);
      navigate('/dashboard');
    } catch (err: any) {
      setError(err.response?.data?.message || 'Verification failed. Please check the code.');
    } finally {
      setLoading(false);
    }
  };

  return (
    <AuthLayout>
      <form onSubmit={handleSubmit} className="space-y-5">
        <div className="text-center space-y-1.5">
          <h2 className="text-xl font-bold text-slate-100 uppercase tracking-wider">
            MFA Verification
          </h2>
          <p className="text-xs text-slate-400">
            Enter the 6-digit verification code generated by your Authenticator app.
          </p>
        </div>

        {error && (
          <div className="p-3 bg-red-500/10 border border-red-500/20 text-red-400 text-xs font-semibold rounded-xl text-center">
            {error}
          </div>
        )}

        <Input
          id="mfa-code"
          label="Verification Code"
          type="text"
          placeholder="e.g. 123456"
          maxLength={6}
          pattern="\d{6}"
          value={code}
          onChange={(e) => setCode(e.target.value.replace(/\D/g, ''))}
          required
          autoFocus
        />

        <div className="flex flex-col space-y-2.5 pt-2">
          <Button type="submit" variant="primary" fullWidth loading={loading}>
            Verify Code
          </Button>
          <Button
            type="button"
            variant="secondary"
            fullWidth
            onClick={() => navigate('/login')}
            disabled={loading}
          >
            Back to Login
          </Button>
        </div>
      </form>
    </AuthLayout>
  );
};
